# Build stage
FROM node:20-alpine AS build

# Define build args and convert to ENV (React needs ENV vars during npm run build)
ARG REACT_APP_INSIGHTS_SERVICE_ENDPOINT
ARG REACT_APP_UPLOAD_SERVICE_ENDPOINT
ARG REACT_APP_MONITOR_SERVICE_ENDPOINT
ARG REACT_APP_STOCK_SERVICE_URL

# EmailJS configuration for contact form (optional - form will gracefully fail if not set)
ARG REACT_APP_EMAILJS_SERVICE_ID
ARG REACT_APP_EMAILJS_TEMPLATE_ID
ARG REACT_APP_EMAILJS_PUBLIC_KEY

ENV REACT_APP_INSIGHTS_SERVICE_ENDPOINT=$REACT_APP_INSIGHTS_SERVICE_ENDPOINT
ENV REACT_APP_UPLOAD_SERVICE_ENDPOINT=$REACT_APP_UPLOAD_SERVICE_ENDPOINT
ENV REACT_APP_MONITOR_SERVICE_ENDPOINT=$REACT_APP_MONITOR_SERVICE_ENDPOINT
ENV REACT_APP_STOCK_SERVICE_URL=$REACT_APP_STOCK_SERVICE_URL
ENV REACT_APP_EMAILJS_SERVICE_ID=$REACT_APP_EMAILJS_SERVICE_ID
ENV REACT_APP_EMAILJS_TEMPLATE_ID=$REACT_APP_EMAILJS_TEMPLATE_ID
ENV REACT_APP_EMAILJS_PUBLIC_KEY=$REACT_APP_EMAILJS_PUBLIC_KEY

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# Production stage
FROM node:20-alpine AS production

RUN npm install -g serve

COPY --from=build /build ./build

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]
