version: '3.8'

services:
  # Upload Service
  upload-service:
    build:
      context: ./backend/upload-service
      dockerfile: .dockerfile
    container_name: finance-analysis-upload
    ports:
      - "8000:8000"
    env_file:
      - ./backend/upload-service/.env

  # Insights Service
  insights-service:
    build:
      context: ./backend/insights-service
      dockerfile: .dockerfile
    container_name: finance-analysis-insights
    ports:
      - "9000:9000"
    env_file:
      - ./backend/insights-service/.env

  # Monitor Service
  monitor-service:
    build:
      context: ./backend/monitor-service
      dockerfile: .dockerfile
    container_name: finance-analysis-monitor
    ports:
      - "8999:8999"
    env_file:
      - ./backend/monitor-service/.env

  # Stock Service
  stock-service:
    build:
      context: ./backend/stock-service
      dockerfile: .dockerfile
    container_name: finance-analysis-stock
    ports:
      - "3004:3004"
    env_file:
      - ./backend/stock-service/.env

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: .dockerfile
      args:
        - REACT_APP_UPLOAD_SERVICE_ENDPOINT=http://localhost:8000
        - REACT_APP_INSIGHTS_SERVICE_ENDPOINT=http://localhost:9000
        - REACT_APP_MONITOR_SERVICE_ENDPOINT=http://localhost:8999
        - REACT_APP_STOCK_SERVICE_URL=http://localhost:3004
    container_name: finance-analysis-frontend
    ports:
      - "3000:3000"
    depends_on:
      - upload-service
      - insights-service
      - monitor-service
      - stock-service
